import type { Project, ThreadItem } from "@/types";

export const projects: Project[] = [
  {
    id: "agent-kanban",
    name: "AgentKanbanBoard",
    path: "/Users/gaoyunchuan/workspace/typescript/AgentKanbanBoard",
    originUrl: "git@github.com:local/AgentKanbanBoard.git",
    promptTemplate: "继续实现 codex-thread-kanban-view",
    aliases: ["kanban", "codex-thread-kanban"],
    active: true
  },
  {
    id: "jvirt-api",
    name: "jvirt-api",
    path: "/Users/gaoyunchuan/workspace/jvirt/jvirt-api",
    originUrl: "git@joycode.jd.com:jvirt/jvirt-api.git",
    aliases: ["jvirt", "虚拟化 API"],
    active: true
  },
  {
    id: "unknown",
    name: "Unknown",
    path: "~/.codex/threads",
    aliases: ["unknown"],
    active: true
  }
];

export const initialThreads: ThreadItem[] = [
  {
    id: "th-9918-runtime-waiting",
    codexSessionId: "550e8400-e29b-41d4-a716-446655440001",
    title: "补齐 ThreadSync 只读同步与事件订阅",
    preview: "实现 app-server thread/list、thread/read、status changed 的只读同步边界。",
    projectId: "agent-kanban",
    cwd: "/Users/gaoyunchuan/workspace/typescript/AgentKanbanBoard",
    branch: "codex/thread-sync",
    boardStatus: "running",
    codexStatus: "running",
    subStatus: "waiting approval",
    taskType: "feature",
    module: "ThreadSync",
    sprint: "S26",
    updatedAt: "2026-06-24 16:42",
    createdAt: "2026-06-24 14:06",
    lastSeenRunningAt: "2026-06-24 16:42",
    notes: "等待确认只读 guard 是否覆盖所有 mutation 方法。"
  },
  {
    id: "th-7721-review-mapper",
    codexSessionId: "550e8400-e29b-41d4-a716-446655440002",
    title: "状态映射：review_pending 稳定窗口",
    preview: "曾经运行且完成 2 分钟后进入待审核，人工 reviewed 不被同步覆盖。",
    projectId: "agent-kanban",
    cwd: "/Users/gaoyunchuan/workspace/typescript/AgentKanbanBoard/src-tauri/services",
    branch: "codex/status-mapper",
    boardStatus: "review_pending",
    codexStatus: "idle",
    subStatus: "completed 18m ago",
    taskType: "review",
    module: "BoardStatusMapper",
    sprint: "S26",
    updatedAt: "2026-06-24 16:08",
    createdAt: "2026-06-24 12:20",
    lastSeenRunningAt: "2026-06-24 15:50",
    notes: "需要检查 reviewed 后再次 running 的状态回退。"
  },
  {
    id: "th-5104-project-match",
    codexSessionId: "550e8400-e29b-41d4-a716-446655440003",
    title: "ProjectMatcher 支持最长路径优先",
    preview: "cwd 精确匹配、子目录匹配、origin URL、alias fallback。",
    projectId: "agent-kanban",
    cwd: "/Users/gaoyunchuan/workspace/typescript/AgentKanbanBoard/src-tauri",
    branch: "codex/project-matcher",
    boardStatus: "review_pending",
    codexStatus: "idle",
    subStatus: "completed 41m ago",
    taskType: "bugfix",
    module: "ProjectMatcher",
    sprint: "S26",
    updatedAt: "2026-06-24 15:46",
    createdAt: "2026-06-23 19:12",
    lastSeenRunningAt: "2026-06-24 15:22",
    notes: "monorepo 子目录命中顺序已补测试。"
  },
  {
    id: "th-4088-ui-filter",
    codexSessionId: "550e8400-e29b-41d4-a716-446655440004",
    title: "固定字段筛选控件压缩成一行",
    preview: "project、status、type、sprint、archive flag 组合筛选。",
    projectId: "agent-kanban",
    cwd: "/Users/gaoyunchuan/workspace/typescript/AgentKanbanBoard/src-ui",
    branch: "codex/ui-filters",
    boardStatus: "untriaged",
    codexStatus: "synced",
    subStatus: "new snapshot",
    taskType: "feature",
    module: "UI",
    sprint: "S26",
    updatedAt: "2026-06-24 11:28",
    createdAt: "2026-06-24 11:26",
    notes: "默认隐藏归档，保留 All Active 入口。"
  },
  {
    id: "th-3370-jvirt-openapi",
    codexSessionId: "550e8400-e29b-41d4-a716-446655440005",
    title: "jvirt OpenAPI schema 校验失败排查",
    preview: "新增字段未进入 schema 生成白名单，导致网关校验失败。",
    projectId: "jvirt-api",
    cwd: "/Users/gaoyunchuan/workspace/jvirt/jvirt-api/pkg/openapi",
    branch: "codex/openapi-schema",
    boardStatus: "running",
    codexStatus: "running",
    subStatus: "typing",
    taskType: "bugfix",
    module: "OpenAPI",
    sprint: "S26",
    updatedAt: "2026-06-24 16:36",
    createdAt: "2026-06-24 15:12",
    lastSeenRunningAt: "2026-06-24 16:36",
    notes: "注意不要改动现有接口出参兼容性。"
  },
  {
    id: "th-2197-docs-readme",
    codexSessionId: "550e8400-e29b-41d4-a716-446655440006",
    title: "补一版本地安装说明",
    preview: "说明 ~/.codex-kanban/app.db 与 projects.yaml 的初始化路径。",
    projectId: "agent-kanban",
    cwd: "/Users/gaoyunchuan/workspace/typescript/AgentKanbanBoard",
    branch: "codex/docs",
    boardStatus: "reviewed",
    codexStatus: "idle",
    subStatus: "reviewed today",
    taskType: "docs",
    module: "Docs",
    sprint: "S26",
    updatedAt: "2026-06-24 10:10",
    createdAt: "2026-06-23 18:10",
    notes: "保留在活跃视图 7 天。"
  },
  {
    id: "th-1003-legacy",
    codexSessionId: "550e8400-e29b-41d4-a716-446655440007",
    title: "旧同步方案：直接解析 session 文件",
    preview: "已废弃，仅保留作为设计取舍记录。",
    projectId: "unknown",
    cwd: "~/.codex/sessions",
    branch: "main",
    boardStatus: "archived",
    codexStatus: "idle",
    subStatus: "archived",
    taskType: "docs",
    module: "Archive",
    sprint: "S25",
    updatedAt: "2026-06-20 09:22",
    createdAt: "2026-06-18 09:22",
    archivedAt: "2026-06-21 12:00",
    notes: "只在 Archived 视图展示。"
  }
];
